[package]
name = "antitelephone"
version = "0.1.0"
authors = ["blackle <isabelle@blackle-mori.com>"]

[dependencies]
typemap = "0.3.3"
serenity = "0.5"
duration-parser = "1.1"
regex = "0.2"
lazy_static = "1.0.0"
chrono = "0.4"
